site_name: marketplace
site_description: Tauros Marketplace
repo_url: https://github.com/luis-zepeda/taurosMarketplace
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/luis-zepeda">luis-zepeda</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
